[2024-05-10T10:27:37.584+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T10:27:37.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ds_project.ds_task manual__2024-05-10T10:27:15.421094+00:00 [queued]>
[2024-05-10T10:27:37.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ds_project.ds_task manual__2024-05-10T10:27:15.421094+00:00 [queued]>
[2024-05-10T10:27:37.635+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-10T10:27:37.660+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ds_task> on 2024-05-10 10:27:15.421094+00:00
[2024-05-10T10:27:37.674+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ds_project', 'ds_task', 'manual__2024-05-10T10:27:15.421094+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/test_dags.py', '--cfg-path', '/tmp/tmpi0v9h0fg']
[2024-05-10T10:27:37.677+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask ds_task
[2024-05-10T10:27:37.683+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1595) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T10:27:37.684+0000] {standard_task_runner.py:63} INFO - Started process 1612 to run task
[2024-05-10T10:27:37.976+0000] {task_command.py:426} INFO - Running <TaskInstance: ds_project.ds_task manual__2024-05-10T10:27:15.421094+00:00 [running]> on host 3514ccd847da
[2024-05-10T10:27:38.071+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ds_project' AIRFLOW_CTX_TASK_ID='ds_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T10:27:15.421094+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T10:27:15.421094+00:00'
[2024-05-10T10:27:38.073+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T10:27:38.106+0000] {logging_mixin.py:188} INFO - Start
[2024-05-10T10:28:02.567+0000] {logging_mixin.py:188} INFO - Data loaded
[2024-05-10T10:28:03.810+0000] {logging_mixin.py:188} INFO - Data preprocessed
[2024-05-10T10:28:03.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T10:28:03.815+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dags.py", line 45, in ds_run_script
    main(paper_info_path, ref_info_path)
  File "/opt/airflow/dags/script.py", line 234, in main
    df_pub_preprocess = add_rec_to_pub(df_pub)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script.py", line 144, in add_rec_to_pub
    df_pub["abstracts_preprocess"] = df_pub["abstracts"].apply(clean_text)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 4924, in apply
    ).apply()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1427, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1507, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/script.py", line 34, in clean_text
    tokens = word_tokenize(text)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 129, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = load(f"tokenizers/punkt/{language}.pickle")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/data.py", line 876, in _open
    return find(path_, path + [""]).open()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

[2024-05-10T10:28:03.855+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ds_project, task_id=ds_task, run_id=manual__2024-05-10T10:27:15.421094+00:00, execution_date=20240510T102715, start_date=20240510T102737, end_date=20240510T102803
[2024-05-10T10:28:03.870+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task ds_task (
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
; 1612)
[2024-05-10T10:28:03.914+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T10:28:03.941+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T10:28:03.946+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
